// Code generated by ifacemaker; DO NOT EDIT.

package yggtorrent

import (
	"io"
)

// Client interface describes wrapped YggTorrent client.
type Client interface {
	// ParseResults read given HTML data to search for torrents results.
	ParseResults(data io.Reader) ([]*Result, error)
	// SearchURL makes a YggTorrent search URL ready to be used through flaresolverr.
	SearchURL(query string, category Category, subcategory SubCategory) string
}
