// Code generated by "stringer --type SubCategory --linecomment"; DO NOT EDIT.

package yggtorrent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Movie-0]
	_ = x[TV-1]
}

const _SubCategory_name = "21832184"

var _SubCategory_index = [...]uint8{0, 4, 8}

func (i SubCategory) String() string {
	if i < 0 || i >= SubCategory(len(_SubCategory_index)-1) {
		return "SubCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubCategory_name[_SubCategory_index[i]:_SubCategory_index[i+1]]
}
